[package]
name = "position_manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "position_manager"

[features]
no-entrypoint = []
no-idl = []
idl-build = []

[dependencies]
anchor-lang = "0.29"
anchor-spl = "0.29"
thiserror = "1"
